"""Add additional columns to Businesses table

Revision ID: 5c4142b8a40a
Revises: 825be0c531e8
Create Date: 2025-11-29 15:16:44.947898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5c4142b8a40a'
down_revision: Union[str, Sequence[str], None] = '825be0c531e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('name', sa.String(), nullable=False))
    op.add_column('businesses', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('businesses', sa.Column('email', sa.String(), nullable=True))
    op.add_column('businesses', sa.Column('website', sa.String(), nullable=True))
    op.add_column('businesses', sa.Column('social_media', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('businesses', sa.Column('logo', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'logo')
    op.drop_column('businesses', 'social_media')
    op.drop_column('businesses', 'website')
    op.drop_column('businesses', 'email')
    op.drop_column('businesses', 'phone')
    op.drop_column('businesses', 'name')
    # ### end Alembic commands ###
